### ISSUE TITLE
MM-WHS数据集问题请教

### ISSUE THREAD

**Issue by DeMo6666-png** [fxxJuses/MICFormer#2]
大佬您好！我是刚接触Multimodal Medical Image Segmentation的新手，想请教下大佬多模态数据集除了MM-WHS还有其他数据集吗？

**Comment by fxxJuses** [comment]
多模态医学图像分割任务公开数据集比较少。其中BraTS是个非常不错的数据集，还有挑战赛的。其他的就是一些眼部的数据集了。

**Comment by DeMo6666-png** [comment]
谢谢您！我刚刚去了解了下BraTS，这个是MRI拍摄的，好像没有CT，MICFormer适用的数据集只有MM-WHS吗？麻烦您啦！

**Comment by fxxJuses** [comment]
MICFormer理论上支持所有的两个模态的分割任务，其他数据集只要满足这个条件都能够使用。我们在写这篇文章的时候也非常苦恼数据集，甚至在最后文章完成时也没有找到第二个公开可用的多模态分割数据集。其他数据集要么质量很差，要么数据没有对应文件。

**Comment by DeMo6666-png** [comment]
谢谢您！
