### ISSUE TITLE
模型输出的维度与标签维度不一致

### ISSUE THREAD

**Issue by caesar-jojo** [fxxJuses/MICFormer#6]
![1-MIC](https://github.com/user-attachments/assets/7a8cbd9f-17d2-4dae-b458-4d26e5d829f9)
您好，我输入的维度如上[b c d w h], 但输出的维度中的d维度发生了变化，导致作Loss损失的时候，跟标签d维度对不上，请问如何解决？

**Comment by fxxJuses** [comment]
你可以尝试将输入维度的d进行黑边填充，以匹配64的倍数。

**Comment by caesar-jojo** [comment]
你好，我接触这个就一两个星期，不太懂，可以给点示范吗？非常感谢，Bro

**Comment by fxxJuses** [comment]
可以参考monai的spatialPadding

**Comment by caesar-jojo** [comment]
好的，谢谢

**Comment by caesar-jojo** [comment]
兄弟，我把54改成64想测试一下，发现还是不行
![1](https://github.com/user-attachments/assets/a1685fb1-4670-4940-ab28-6c847d54cde1)
